#!/usr/bin/env python3
# AI-Assisted: Claude Code (model: claude-sonnet-5) - Added the table-coverage report (009 tasks
# T054/T065, FR-018, rule 3): runs `check_table_coverage` against a REAL acquisition (never a
# fixture directory listing, per rule 3) and writes table names, row counts, and finding codes
# only.
"""Run ``check_table_coverage`` against a real acquisition, and report what it finds.

`pipeline.acquire.wahapedia.check_table_coverage` (009 T027/T028) has been unit-tested against
synthetic fixtures since Setup, but never run against an acquisition -- and per FR-018/rule 3,
table presence and population is the one category of claim in this feature that may not be
fixture-backed. This is that run::

    python tools/table_coverage_report.py                 # live, configured source
    python tools/table_coverage_report.py --offline --fixtures fixtures/minimal

Text-free (table names and row counts only) and non-destructive: the acquisition lives inside an
ephemeral workspace discarded at run end, and nothing under ``data/``, ``curation/``, or
``state/`` is written.
"""

from __future__ import annotations

import argparse
import dataclasses
import sys
from collections.abc import Sequence
from datetime import UTC, datetime
from pathlib import Path
from typing import Final

from pipeline.acquire.detail_source import acquire_detail, read_detail
from pipeline.acquire.http import AcquisitionError
from pipeline.acquire.wahapedia import check_table_coverage
from pipeline.config import ConfigError, DetailAcquisitionMode, load_config, repo_root
from pipeline.exit_codes import ExitCode
from pipeline.parse.equipment_grammar import EQUIPMENT_TABLE
from pipeline.workspace import workspace

PROG: Final = "table_coverage_report.py"
REPORTS_DIR: Final = Path("reports") / "009-diagnosis"

#: Every table `curate/` actually reads from `detail`, by grep of every `detail.get(...)` /
#: `detail[...]` call site in `pipeline/curate/`. `Enhancements.csv` is acquired
#: (`EXPORT_FILES`) but consumed by no code path today -- deliberately NOT listed here, since
#: this measures what the BUILD consumes, and its absence from this list is itself a finding
#: (recorded in the rendered report, not silently reconciled).
CONSUMED_TABLES: Final[tuple[str, ...]] = (
    "Datasheets.csv",
    "Datasheets_options.csv",
    "Datasheets_unit_composition.csv",
    "Datasheets_models_cost.csv",
    "Source.csv",
    "Datasheets_keywords.csv",
    "Datasheets_models.csv",
    "Datasheets_wargear.csv",
    "Datasheets_abilities.csv",
    "Datasheets_leader.csv",
    "Detachments.csv",
    "Detachment_abilities.csv",
    EQUIPMENT_TABLE,
    "Abilities.csv",
)


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(prog=PROG, description=__doc__)
    parser.add_argument("--fixtures", type=Path, default=None)
    parser.add_argument("--offline", action="store_true")
    parser.add_argument("--repo", type=Path, default=None)
    parser.add_argument("--print-only", action="store_true")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    root = args.repo or repo_root()

    try:
        config = load_config()
        # Captured BEFORE the rebind below, or the report says "config default is `csv`" no
        # matter what the configured default actually is (009 rung R01a, ledger 5a).
        configured_mode = config.detail_acquisition_mode
        config = dataclasses.replace(config, detail_acquisition_mode=DetailAcquisitionMode.CSV)
        with workspace(root) as work:
            acquisition, payloads = acquire_detail(
                config, fixtures_dir=args.fixtures, offline=args.offline, workspace=work
            )
            detail = read_detail(config, payloads)
            findings = check_table_coverage(detail, consumed_tables=CONSUMED_TABLES)
            counts = {
                table: (len(detail[table].rows) if table in detail else 0)
                for table in CONSUMED_TABLES
            }
    except ConfigError as exc:
        print(f"{PROG}: {exc}", file=sys.stderr)
        return int(ExitCode.CONFIG_ERROR)
    except AcquisitionError as exc:
        print(f"{PROG}: {exc}", file=sys.stderr)
        return int(exc.exit_code)

    generated_at = datetime.now(UTC).isoformat()
    lines = [
        "<!-- AI-Assisted: Claude Code (model: claude-sonnet-5) - Generated by "
        "tools/table_coverage_report.py (009 T054/T065). -->",
        "# Table coverage against a real acquisition",
        "",
        f"- Generated: `{generated_at}`",
        f"- Source: `{acquisition.source_base_url}`",
        f"- Mode forced to `csv` for this measurement "
        f"(config default is `{configured_mode.value}`)",
        "",
        "| Table | Rows | Coverage |",
        "|---|---:|---|",
    ]
    blocking_tables = {f.detail["table"] for f in findings}
    for table in CONSUMED_TABLES:
        status = "SRC-TABLE-MISSING" if table in blocking_tables else "present"
        lines.append(f"| `{table}` | {counts[table]} | {status} |")
    lines.append("")
    lines.append(f"**{len(findings)} of {len(CONSUMED_TABLES)} consumed tables missing/empty.**")
    lines.append("")
    lines.append(
        "`Enhancements.csv` is acquired (`EXPORT_FILES`) but consumed by no code path in "
        "`pipeline/curate/` today -- not counted above; a genuine finding, not a coverage gap "
        "this measurement is claiming."
    )
    rendered = "\n".join(lines) + "\n"

    if args.print_only:
        print(rendered)
    else:
        destination = root / REPORTS_DIR / f"table-coverage-{generated_at[:10]}.md"
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(rendered, encoding="utf-8", newline="\n")
        print(f"{PROG}: wrote {destination}")

    print(f"{PROG}: {len(findings)} of {len(CONSUMED_TABLES)} consumed tables missing/empty")
    return int(ExitCode.SUCCESS)


if __name__ == "__main__":
    raise SystemExit(main())
